version: '2'

services:
  app:
    image: eeacms/nfi-search
    container_name: nfi_search_app
    env_file:
    - docker/postgres.env
    - docker/app.env
    depends_on:
    - postgres
    ports:
    - 8000:8000

  postgres:
    image: eeacms/postgres:9.6
    container_name: nfi_search_postgres
    env_file:
    - docker/postgres.env
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: frontend=yes
    volumes:
    - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local
