version: '2'

services:

  app:
    image: eeacms/fise.nfi.search:latest
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
      - docker/app.env
    volumes:
      - data-files:/var/local/fise.search/data_files
      - import-files:/var/local/fise.search/import_files

  nginx:
    image: nginx:latest
    environment:
      NGINX_CONF: |-
        upstream app {
          ip_hash;
          server app:${DJANGO_PORT};
        }
        server {
          listen 80 default_server;
          server_name _;
          client_max_body_size 50M;
          access_log /var/log/nginx/access.log main;
          location / {
            uwsgi_pass app;
            include uwsgi_params;
          }
          location ~* \.(jpg|jpeg|png|gif|ico|css|js)$$ {
            uwsgi_pass app;
            include uwsgi_params;
            expires 365d;
          }
        }
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    depends_on:
      - app

volumes:
  data-files:
    driver: local
  import-files:
    driver: local
