version: '2'

services:
  app:
    image: eeacms/fise.nfi.search:latest
    container_name: nfi.app
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
      - docker/app.env
    depends_on:
      - postgres
    ports:
      - 8000:8000

  nginx:
    image: nginx:stable-alpine
    container_name: nfi.nginx
    environment:
      TZ: Europe/Copenhagen
      NGINX_CONF: |-
        server {
          listen 80;
          access_log /var/log/nginx/access.log main;
          location /static {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 1d;
            root /var/local/fise.nfi.search;
          }
        }
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    depends_on:
      - app
    volumes:
      - static-files:/var/local/fise.nfi.search/static:ro

  postgres:
    image: eeacms/postgres:latest
    container_name: nfi.db
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local
  static-files:
    driver: local
