version: '2'

services:
  app:
    image: eeacms/fise.nfi.search:latest
    container_name: nfi.app
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
      - docker/app.env
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    image: eeacms/postgres:latest
    container_name: nfi.db
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local
  static-files:
    driver: local
