version: '2'

services:

  tika:
    image: logicalspark/docker-tikaserver

  app:
    image: eeacms/fise.nfi.search:latest
    container_name: nfi.app
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - docker/postgres.env
      - docker/app.env
    volumes:
      - static-files:/var/local/nfi_search/static_files
    depends_on:
      - tika

volumes:
  static-files:
    driver: local
