# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180613_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='search.Document'),
        ),
        migrations.AlterField(
            model_name='geographicbounds',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_bounds', to='search.Document'),
        ),
    ]
