# Generated by Django 2.0.6 on 2018-06-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20180618_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='search.DCountry'),
        ),
        migrations.AlterField(
            model_name='document',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DCountry'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DDataSet'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DDataSource'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DDataType'),
        ),
        migrations.AlterField(
            model_name='document',
            name='info_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DInfoLevel'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.Organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DResourceType'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DTopicCategory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DFileType'),
        ),
    ]
