# Generated by Django 2.0.6 on 2018-06-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20180622_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=200)),
                ('original_path_root', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'DocumentBatches',
                'db_table': 'document_batch',
            },
        ),
        migrations.RenameField(
            model_name='file',
            old_name='location',
            new_name='original_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='batch',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.DocumentImportBatch'),
        ),
    ]
