# Generated by Django 2.0.6 on 2018-08-23 13:20

from django.db import migrations, models
import fise_search.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20180709_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='country',
        ),
        migrations.AddField(
            model_name='document',
            name='countries',
            field=models.ManyToManyField(db_table='document_country', related_name='documents', to='search.DCountry'),
        ),
        migrations.AddField(
            model_name='documentimportbatch',
            name='posix_original_path',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, storage=fise_search.search.models.FileStorage(), upload_to=fise_search.search.models.get_upload_path),
        ),
    ]
