# Generated by Django 2.2.7 on 2019-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20191121_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
