# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcountry',
            options={'verbose_name_plural': 'DCountries'},
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='country',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DCountry'),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dcountry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ddataset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ddatasource',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ddatatype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dfiletype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dinfolevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dkeyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dlanguage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dnutslevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='country',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DCountry'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DDataSet'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DDataSource'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DDataType'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='info_level',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DInfoLevel'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.Organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DResourceType'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topic_category',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DTopicCategory'),
        ),
        migrations.AlterField(
            model_name='documentkeyword',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    primary_key=True, serialize=False,
                                    to='search.Document'),
        ),
        migrations.AlterField(
            model_name='documentkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DKeyword'),
        ),
        migrations.AlterField(
            model_name='documentnutslevel',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    primary_key=True, serialize=False,
                                    to='search.Document'),
        ),
        migrations.AlterField(
            model_name='documentnutslevel',
            name='nuts_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DNutsLevel'),
        ),
        migrations.AlterField(
            model_name='dresourcetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dtopiccategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.Document'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DFileType'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filelanguage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    primary_key=True, serialize=False,
                                    to='search.File'),
        ),
        migrations.AlterField(
            model_name='filelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='search.DLanguage'),
        ),
        migrations.AlterField(
            model_name='geographicbounds',
            name='document',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='search.Document'),
        ),
        migrations.AlterField(
            model_name='geographicbounds',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True,
                                   serialize=False, verbose_name='ID'),
        ),
    ]
