# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_switch_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='responsible_person',
            field=models.TextField(blank=True, null=True),
        ),
    ]
