# Generated by Django 2.0.6 on 2018-07-09 09:31

from django.db import migrations, models
import django.db.models.deletion
import nfi_search.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20180628_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=512, null=True, storage=nfi_search.search.models.FileStorage, upload_to=nfi_search.search.models.get_upload_path)),
                ('original_path', models.TextField(blank=True, null=True)),
                ('external_link', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='search.Document')),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.DFileType')),
                ('languages', models.ManyToManyField(db_table='document_file_language', related_name='files', to='search.DLanguage')),
            ],
            options={
                'db_table': 'document_file',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='document',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='languages',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
