# Generated by Django 2.2.7 on 2019-11-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20180823_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='parent',
        ),
    ]
