# Generated by Django 2.2.7 on 2019-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_remove_document_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='higher_level_docs',
            field=models.ManyToManyField(related_name='lower_level_backrefs', to='search.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='lower_level_docs',
            field=models.ManyToManyField(related_name='higher_level_backrefs', to='search.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='same_level_docs',
            field=models.ManyToManyField(related_name='same_level_backrefs', to='search.Document'),
        ),
    ]
