# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_extend_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentkeyword',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='documentkeyword',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentkeyword',
            name='keyword',
        ),
        migrations.AlterUniqueTogether(
            name='documentnutslevel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='documentnutslevel',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentnutslevel',
            name='nuts_level',
        ),
        migrations.AlterUniqueTogether(
            name='filelanguage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='filelanguage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filelanguage',
            name='language',
        ),
        migrations.DeleteModel(
            name='DocumentKeyword',
        ),
        migrations.DeleteModel(
            name='DocumentNutsLevel',
        ),
        migrations.DeleteModel(
            name='FileLanguage',
        ),
    ]
