# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180613_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(db_table='document_keyword', related_name='documents', to='search.DKeyword'),
        ),
        migrations.AddField(
            model_name='document',
            name='nuts_levels',
            field=models.ManyToManyField(db_table='document_nut_level', related_name='documents', to='search.DNutsLevel'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='languages',
            field=models.ManyToManyField(db_table='file_language', related_name='files', to='search.DLanguage'),
        ),
    ]
