# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180618_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='batch',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
